# Generated by Django 3.2.16 on 2022-11-22 05:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('need_by_date', models.DateField()),
                ('maximum_quotes_desired', models.IntegerField()),
                ('quote_cap_reached', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('in_contract', models.BooleanField(default=False)),
                ('author_notified', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_author', to=settings.AUTH_USER_MODEL)),
                ('liked', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='SellerQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('expiry_date', models.DateField(auto_now_add=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('author_notified', models.BooleanField(default=False)),
                ('buyer_notified', models.BooleanField(default=False)),
                ('buyer_hidden', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_quote_user', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.buyerrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='buyer_request_attachments/')),
                ('buyer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.buyerrequest')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteRejectedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieved', models.BooleanField(default=False)),
                ('seller_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.sellerquote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoterejectednotification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='seller_quote_attachments/')),
                ('seller_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.sellerquote')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_content', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user_read', models.BooleanField(default=False)),
                ('quote_regarding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.sellerquote')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL)),
                ('request_regarding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.buyerrequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
